title: Andrew的技术博客
description: 分享AI、编程和技术心得
author: Andrew
email: your-email@example.com
baseurl: ""
url: ""

# 社交媒体链接
github_username: your-github-username
twitter_username: your-twitter-username

# 主题设置
theme: minima

# 博客设置
permalink: /:year/:month/:day/:title/
show_excerpts: true

# Markdown 设置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 分页设置
paginate: 5
paginate_path: "/blog/page:num/"

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# 排除的文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
